# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'dancook'
tagline:          ''
description:      'profile/blog'
url:              'https://1dancook.github.io'
baseurl:              'https://1dancook.github.io'

author:
  name:           'Daniel Cook'
  url:            https://1dancook.github.io

paginate:         5
plugins:             [jekyll-paginate]
paginate_path:    "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/1dancook/1dancook.github.io
