# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'dancook'
tagline:          ''
description:      'profile/blog'
url:              'https://1dancook.github.io'

author:
  name:           'Daniel Cook'
  url:            https://1dancook.github.io

paginate:         5
plugins:          [jekyll-paginate]
paginate_path:    "page:num"
